"""
script_generator.py

Responsibility:
  Converts structured test case JSON (from test_generator.py) into
  executable Python Appium scripts. No LLM required — pure schema mapping.

  Supports actions: tap, enterText, longPress, swipe, back

  Locator priority:
    1. resource_id  → AppiumBy.ID
    2. content_desc → AppiumBy.ACCESSIBILITY_ID
    3. text         → UiSelector text match (fallback)
"""

import json
import os
from pathlib import Path


# ── Action templates ──────────────────────────────────────────────────────────

def _locator_code(target: str) -> str:
    """
    Returns the Python Appium locator expression for a given target string.
    Heuristic: if target contains '/' or ':id/' it's a resource-id,
    otherwise treat it as accessibility-id.
    """
    if not target:
        return 'AppiumBy.ACCESSIBILITY_ID, "unknown"'
    if "/" in target or ":id/" in target:
        return f'AppiumBy.ID, "{target}"'
    return f'AppiumBy.ACCESSIBILITY_ID, "{target}"'


def _tap(step: dict) -> str:
    loc = _locator_code(step.get("target", ""))
    return f'    driver.find_element({loc}).click()'


def _enter_text(step: dict) -> str:
    loc = _locator_code(step.get("target", ""))
    value = step.get("value", "").replace('"', '\\"')
    return (
        f'    el = driver.find_element({loc})\n'
        f'    el.clear()\n'
        f'    el.send_keys("{value}")'
    )


def _long_press(step: dict) -> str:
    loc = _locator_code(step.get("target", ""))
    return (
        f'    el = driver.find_element({loc})\n'
        f'    ActionChains(driver).click_and_hold(el).pause(1.5).release().perform()'
    )


def _swipe(_step: dict) -> str:
    return (
        '    size = driver.get_window_size()\n'
        '    driver.swipe(\n'
        '        start_x=size["width"] // 2, start_y=int(size["height"] * 0.75),\n'
        '        end_x=size["width"] // 2,   end_y=int(size["height"] * 0.25),\n'
        '        duration=500,\n'
        '    )'
    )


def _back(_step: dict) -> str:
    return '    driver.back()'


_ACTION_MAP = {
    "tap":       _tap,
    "entertext": _enter_text,
    "enterText": _enter_text,
    "longpress": _long_press,
    "longPress": _long_press,
    "swipe":     _swipe,
    "back":      _back,
}

# ── Script template ───────────────────────────────────────────────────────────

_SCRIPT_HEADER = '''\
"""
Auto-generated Appium test script.
Generated by script_generator.py — do not edit manually.

Run:
  python {filename}

Requires:
  - Appium server running on localhost:4723
  - Android emulator running with the target app installed
  - pip install Appium-Python-Client
"""

import os
import time
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.common.action_chains import ActionChains

APP_PACKAGE  = os.environ.get("APP_PACKAGE",  "{app_package}")
APP_ACTIVITY = os.environ.get("APP_ACTIVITY", "{app_activity}")
APPIUM_URL   = os.environ.get("APPIUM_URL",   "http://localhost:4723")


def build_driver():
    options = UiAutomator2Options()
    options.platform_name        = "Android"
    options.app_package          = APP_PACKAGE
    options.app_activity         = APP_ACTIVITY
    options.no_reset             = True
    options.auto_grant_permissions = True
    options.new_command_timeout  = 300
    return webdriver.Remote(APPIUM_URL, options=options)

'''

_TEST_FUNCTION_TEMPLATE = '''\
def {func_name}(driver):
    """
    {test_case_id}: {title}
    Objective: {objective}
    Expected:  {expected_result}
    """
{body}

'''

_MAIN_TEMPLATE = '''\
if __name__ == "__main__":
    driver = build_driver()
    time.sleep(2)
    try:
{calls}
    finally:
        driver.quit()
'''


# ── Public API ────────────────────────────────────────────────────────────────

def generate_script(
    test_cases: list,
    output_path: str,
    app_package: str = "com.android.settings",
    app_activity: str = ".Settings",
) -> str:
    """
    Converts a list of structured test case dicts into a single executable
    Python Appium script and writes it to output_path.

    Args:
        test_cases:   List of test case dicts (from test_generator.py)
        output_path:  Where to write the .py script
        app_package:  Android package to launch
        app_activity: Android activity to launch

    Returns:
        Path to the generated script file
    """
    if not test_cases:
        print("[script_generator] No test cases to convert.")
        return ""

    filename = Path(output_path).name
    lines = [_SCRIPT_HEADER.format(
        filename=filename,
        app_package=app_package,
        app_activity=app_activity,
    )]

    func_names = []

    for tc in test_cases:
        tc_id     = tc.get("test_case_id") or tc.get("id", "TC000")
        title     = tc.get("title", tc.get("objective", ""))
        objective = tc.get("objective", "")
        expected  = tc.get("expected_result", "")
        steps     = tc.get("steps", [])

        func_name = f"test_{tc_id.lower().replace('-', '_')}"
        func_names.append(func_name)

        step_lines = []
        for i, step in enumerate(steps, 1):
            action = step.get("action", "").lower()
            handler = _ACTION_MAP.get(action) or _ACTION_MAP.get(
                next((k for k in _ACTION_MAP if k.lower() == action), ""), None
            )
            if handler is None:
                step_lines.append(f"    # Step {i}: unsupported action '{action}' — skipped")
                continue
            step_lines.append(f"    # Step {i}: {action} → {step.get('target', '')}")
            step_lines.append(handler(step))
            step_lines.append("    time.sleep(0.5)")

        body = "\n".join(step_lines) if step_lines else "    pass  # no steps"

        lines.append(_TEST_FUNCTION_TEMPLATE.format(
            func_name=func_name,
            test_case_id=tc_id,
            title=title,
            objective=objective,
            expected_result=expected,
            body=body,
        ))

    # main block
    calls = "\n".join(
        f"        print('Running {fn}...')\n        {fn}(driver)\n        print('  DONE')"
        for fn in func_names
    )
    lines.append(_MAIN_TEMPLATE.format(calls=calls))

    script_content = "\n".join(lines)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    print(f"[script_generator] Generated {len(test_cases)} test function(s) → {output_path}")
    return output_path


def load_test_cases(json_path: str) -> list:
    """Reads test cases from a JSON file."""
    if not os.path.exists(json_path):
        print(f"[script_generator] File not found: {json_path}")
        return []
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)
